# File to setup schedulers
- name: Setup descheduler
  hosts: kube_controller
  tags: setup_descheduler

  tasks:
    - name: Clone descheduler
      ansible.builtin.git:
        repo: https://github.com/AlfredDaimari/descheduler.git      
        dest: "/home/{{inventory_hostname}}/descheduler"

    - name: Add as safe directory
      ansible.builtin.command: "git config --global --add safe.directory /home/{{inventory_hostname}}/descheduler"

# switch descheduler branch
- name: Switch descheduler branch
  hosts: kube_controller
  tags: switch_des_branch

  tasks:
    - name: Switch descheduler branch
      ansible.builtin.git:
        repo: https://github.com/AlfredDaimari/descheduler.git
        dest: "/home/{{inventory_hostname}}/descheduler"
        version: "{{branch_name}}"
        force: yes

# setup kubernetes descheduler
- name: Run descheduler
  hosts: kube_controller
  tags: run_descheduler

  tasks:
    - name: Run descheduler rbac
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl create -f kubernetes/base/rbac.yaml
      args:
        chdir: "/home/{{inventory_hostname}}/descheduler"

    - name: Run descheduler configmap
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl create -f kubernetes/base/configmap.yaml
      args:
        chdir: "/home/{{inventory_hostname}}/descheduler"

    - name: Run descheduler deployment
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl create -f kubernetes/deployment/deployment.yaml
      args:
        chdir: "/home/{{inventory_hostname}}/descheduler"


- name: Remove descheduler
  hosts: kube_controller
  tags: remove_descheduler

  tasks:
    - name: Remove descheduler rbac
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl delete -f kubernetes/base/rbac.yaml
      args:
        chdir: "/home/{{inventory_hostname}}/descheduler"
    
    - name: Remove descheduler configmap
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl delete -f kubernetes/base/configmap.yaml
      args:
        chdir: "/home/{{inventory_hostname}}/descheduler"

    - name: Remove descheduler deployment
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl delete -f kubernetes/deployment/deployment.yaml
      args:
        chdir: "/home/{{inventory_hostname}}/descheduler"

# setup metrics server
- name: Setup kubernetes metrics server
  hosts: kube_controller
  tags: setup_metrics_server

  tasks:
    - name: setup metrics server for scheduler usage
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

# setup poseidon scheduler
- name: Run poseidon firmament scheduler
  hosts: kube_controller
  tags: run_poseidon

  tasks:
    - name: Run poseidon scheduler firmament deployment
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/kubernetes-sigs/poseidon/master/deploy/firmament-deployment.yaml

    - name: Run poseidon scheduler deployment
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/kubernetes-sigs/poseidon/master/deploy/poseidon-deployment.yaml

# remove poseidon scheduler
- name: Remove poseidon firmament scheduler
  hosts: kube_controller
  tags: remove_poseidon

  tasks:
    - name: Remove poseidon scheduler firmament deployment
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl delete -f https://raw.githubusercontent.com/kubernetes-sigs/poseidon/master/deploy/firmament-deployment.yaml

    - name: Remove poseidon scheduler deployment
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/kubernetes-sigs/poseidon/master/deploy/poseidon-deployment.yaml




