# setup deathstar benchmark
- name: Setup deathstar benchmark
  hosts: servers
  tags: setup_deathstar

  tasks:
    - name: Setup deathstar
      ansible.builtin.git:
        repo: https://github.com/AlfredDaimari/DeathStarBench.git         
        dest: "/home/{{inventory_hostname}}/deathstar"

    - name: Add as safe directory
      ansible.builtin.command: git config --global --add safe.directory /home/vagrant/deathstar

- name: Setup docker.io
  hosts: servers
  tags: setup_docker
  
  tasks:
    - name: setup docker
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.command: snap install docker

    - name: setup a docker image repository
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.command: docker run -d -p 5000:5000 --name registry registry:2.7

# build images in each node
- name: Build image on each node
  hosts: servers
  tags: build_image

  tasks:
    - name: build hotel reservation images on local node
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: sh kubernetes/scripts/build-docker-images.sh
      args:
        chdir: "/home/{{inventory_hostname}}/deathstar/hotelReservation"

- name: Delete images on each node
  hosts: servers
  tags: delete_image

  tasks:
    - name: delete images on local node
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: docker image prune --all -f

    - name: remove local docker repository
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: docker stopp registry

# switch branch
- name: Switch deathstar branch
  hosts: kube_controller
  tags: switch_branch
  
  tasks:
    - name: switch deathstar branch
      ansible.builtin.git:
        repo: https://github.com/AlfredDaimari/DeathStarBench.git       
        dest: "/home/{{inventory_hostname}}/deathstar"
        version: "{{ branch_name }}" 
        force: yes

# Setup hotel reservation deathstar benchmark
- name: Setup hotel reservation deathstar benchmark
  hosts: kube_controller
  tags: setup_hotel_reservation
  tasks:
    - name: Setup hotel reservation
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.command: "kubectl apply -Rf /home/{{inventory_hostname}}/deathstar/hotelReservation/kubernetes/"

# Remove hotel reservation deathstar benchmark
- name: Remove hotel reservation deathstar benchmark
  hosts: kube_controller
  tags: remove_hotel_reservation
  tasks:
    - name: remove hotel reservation
      ansible.builtin.command: "kubectl delete -Rf /home/{{inventory_hostname}}/deathstar/hotelReservation/kubernetes/"

