# setup deathstar benchmark
- name: Setup deathstar benchmark
  hosts: servers
  tags: setup_deathstar

  tasks:
    - name: Setup deathstar
      ansible.builtin.git:
        repo: https://github.com/AlfredDaimari/DeathStarBench.git         
        dest: "/home/{{inventory_hostname}}/deathstar"

    - name: Add as safe directory
      ansible.builtin.command: "git config --global --add safe.directory /home/{{inventory_hostname}}/deathstar"

- name: Setup docker.io
  hosts: servers
  tags: setup_docker
  
  tasks:
    - name: setup docker
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.command: snap install docker

    - name: setup a docker image repository
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.command: docker run -d -p 5000:5000 --name registry registry:2.7

# build images in each node
- name: Build image on each node hotel reservation
  hosts: servers
  tags: build_image_hotel

  tasks:
    - name: build hotel reservation images on local node
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: sh kubernetes/scripts/build-docker-images.sh
      args:
        chdir: "/home/{{inventory_hostname}}/deathstar/hotelReservation"

- name: Build image on each node media microservices
  hosts: servers
  tags: build_image_media
  
  tasks:
    - name: build media microservices images on local node
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: sh kubernetes/scripts/build-docker-images.sh
      args:
        chdir: "/home/{{inventory_hostname}}/deathstar/mediaMicroservices"

- name: Delete images on each node
  hosts: servers
  tags: delete_image

  tasks:
    - name: delete images on local node
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: docker image prune --all -f

    - name: stop local docker repository
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: docker stop registry

    - name: remove local docker registry
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.shell: docker rm registry

# switch branch
- name: Switch deathstar branch
  hosts: kube_controller
  tags: switch_death_branch
  
  tasks:
    - name: switch deathstar branch
      ansible.builtin.git:
        repo: https://github.com/AlfredDaimari/DeathStarBench.git       
        dest: "/home/{{inventory_hostname}}/deathstar"
        version: "{{ branch_name }}" 
        force: yes

# Setup hotel reservation deathstar benchmark
- name: Setup hotel reservation deathstar benchmark
  hosts: kube_controller
  tags: setup_hotel_reservation
  tasks:
    - name: Setup hotel reservation
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.command: "kubectl apply -Rf /home/{{inventory_hostname}}/deathstar/hotelReservation/kubernetes/"

# Remove hotel reservation deathstar benchmark
- name: Remove hotel reservation deathstar benchmark
  hosts: kube_controller
  tags: remove_hotel_reservation
  tasks:
    - name: remove hotel reservation
      ansible.builtin.command: "kubectl delete -Rf /home/{{inventory_hostname}}/deathstar/hotelReservation/kubernetes/"


# Setup mediaMicroservices deathstar benchmark
- name: Setup media microservices deathstar benchmark
  hosts: kube_controller
  tags: setup_media_microservices
  tasks:
    - name: Setup media microservices
      ansible.builtin.command: "kubectl apply -Rf /home/{{inventory_hostname}}/deathstar/mediaMicroservices/kubernetes/"


# Remove mediaMicroservices deathstar benchmark
- name: Remove media microservices deathstar benchmark
  hosts: kube_controller
  tags: remove_media_microservices
  tasks:
    - name: remove media microservices
      ansible.builtin.command: "kubectl delete -Rf /home/{{inventory_hostname}}/deathstar/mediaMicroservices/kubernetes/"

# Setup socialNetwork deathstar benchmark
- name: Setup social network deathstar benchmark
  hosts: kube_controller
  tags: setup_social_network
  tasks:
    - name: setup social network
      ansible.builtin.command: "kubectl apply -Rf /home/{{inventory_hostname}}/deathstar/socialNetwork/kubernetes/"


# Remove socialNetwork deathstar benchmark
- name: Remove social network deathstar benchmark
  hosts: kube_controller
  tags: remove_social_network
  tasks:
    - name: remove social network
      ansible.builtin.command: "kubectl delete -Rf /home/{{inventory_hostname}}/deathstar/socialNetwork/kubernetes/"
