---
# Clone scaphandre on cluster
- name: Install scaphandre on each machine
  hosts: servers
  tags: install_scaph

  tasks:
  - name: Update packages
    become: yes
    become_user: root
    become_method: sudo
    apt:
      update_cache: yes

  - name: Install libssl-dev
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.apt:
      name: libssl-dev
      state: latest

  - name: Install pkg-config
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.apt:
      name: pkg-config
      state: latest

  - name: Install build-essential
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.apt:
      name: build-essential
      state: latest

  - name: Update curl
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.apt:
      name: curl
      state: latest

  - name: Update git
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.apt:
      name: git
      state: latest

  - name: Clone scaphandre
    ansible.builtin.git:
      repo: https://github.com/hubblo-org/scaphandre.git
      dest: "/home/{{inventory_hostname}}/scaphandre"

  - name: Download cargo installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'

  - name: install rust/cargo
    ansible.builtin.shell: /tmp/sh.rustup.rs -y

  - name: Build scaph
    ansible.builtin.command: "/home/{{inventory_hostname}}/.cargo/bin/cargo build --features qemu"
    args:
      chdir: "/home/{{inventory_hostname}}/scaphandre"

# install the requirments needed to setup a virtual file system
- name: Setup 9p and virtiofs 
  hosts: servers
  tags: setup_virtio
  vars:
    scheduler: 'kube-default'
    algo: 'algo-default'
  
  tasks:
  - name: Install 9p virtio driver
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.apt:
      name: qemu-guest-agent
      state: latest

  - name: Add 9p to initramfs
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.copy:
      src: /srv/remote/initramfs-modules
      dest: /etc/initramfs-tools/modules
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Update the initramfs
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.command: update-initramfs -u
  
  - name: Add 9p to loaded kernel modules
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.copy:
      src: /srv/remote/kernel-modules
      dest: /etc/modules
      owner: root
      group: root
      mode: u=rw,g=r,o=r
  
  - name: Reebot the machine
    become: yes
    become_user: root
    become_method: sudo
    reboot:
      reboot_timeout: 600

  - name: Make scaphandre mount directory
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.command: mkdir /var/scaphandre

  - name: Make scaphandre json output mount directory
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.command: mkdir /var/json

  - name: Mount the scaphandre directory
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.command: 'mount -t virtiofs {{inventory_hostname}}-scaph /var/scaphandre'

  - name: Mount the json output directory
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.command: 'mount -t virtiofs {{inventory_hostname}}-json /var/json'

  - name: Create the json write file
    become: yes
    become_user: root
    become_method: sudo
    ansible.builtin.command: 'touch /var/json/{{inventory_hostname}}-{{scheduler}}-{{algo}}-report.json'

# setup scaphandre as a service
- name: Create scaphandre service
  hosts: servers
  tags: setup_scaph

  # variables required by the scaphandre creation
  # scheduler
  # algo
  # requests per second
  # duration

  # add max top consumers to limit the json file
  tasks:
    - name: Create scaphandre service for json logs every 5 seconds
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.copy:
        dest: /etc/systemd/system/scaphandre.service
        content: |
          [Unit]
          Description=Scaphandre Service
          After=network.target

          [Service]
          ExecStart=/home/vagrant/scaphandre/target/debug/scaphandre --vm json -s 5 -f /var/json/{{inventory_hostname}}-{{scheduler}}-{{algo}}-{{req_per_sec}}reqs-{{dur}}dur-report.json --resources
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

- name: Enable scaphandre
  hosts: servers
  tags: enable_scaph

  tasks:
    - name: Enable scaphandre service
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.systemd:
        name: scaphandre
        enabled: yes
        state: started

- name: Disable scaphandre
  hosts: servers
  tags: disable_scaph
  
  tasks:
    - name: Disable scaphandre service
      become: yes
      become_user: root
      become_method: sudo
      ansible.builtin.systemd:
        name: scaphandre
        enabled: no
        state: stopped

